import { Difficulty, QuestionStatus, SolutionType, Track, type Question } from "./types";

export const BLIND75_QUESTIONS: Question[] = [
	{
		id: "blind-balanced-brackets",
		questionNumber: 1,
		path: "balanced-brackets",
		title: "Balanced Brackets",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/study/blind75/questions/algo/array-balanced-brackets",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: `Given a string containing only bracket characters, determine whether it is properly balanced.

A string is balanced when:
1. Every opening bracket is closed by the same type.
2. Brackets close in the correct order.
3. Any nested subset inside a matched pair is also balanced.

Constraints:
- 1 <= str.length <= 1000
- Characters are limited to (, ), {, }, [ and ].`,
		cardSummary: "Determine whether a bracket string is properly balanced under matching/order rules.",
		approach:
			"Validate constraints first (length and supported tokens). Then scan left-to-right with a stack: push opening brackets; for closing brackets, ensure the top is the matching opener before popping. Return false on any mismatch and true only if the stack is empty at the end.",
		complexity: "Time: O(n), Space: O(n).",
	},
	{
		id: "blind-find-duplicates-in-array",
		questionNumber: 2,
		path: "find-duplicates-in-array",
		title: "Find Duplicates in Array",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/study/blind75/questions/algo/array-find-duplicate",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: `Given an array of integers numbers, determine whether the array contains any duplicate values. A duplicate is defined as any number that appears more than once in the array.

Examples:
- [5, 7, 1, 3] => false
- [10, 7, 0, 0, 9] => true
- [3, 2, 6, 5, 0, 3, 10, 3, 10, 5] => true

Constraints:
- 1 <= numbers.length <= 10,000
- -1,000,000 <= numbers[i] <= 1,000,000`,
		cardSummary: "Detect whether any integer appears more than once in an array.",
		approach:
			"Scan the array once while storing seen values in a Set. For each number, return true immediately if it is already in the Set; otherwise add it and continue. If the loop finishes, every value was unique so return false.",
		complexity: "Time: O(n), Space: O(n).",
	},
	{
		id: "blind-find-missing-number-in-sequence",
		questionNumber: 3,
		path: "find-missing-number-in-sequence",
		title: "Find Missing Number in Sequence",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: `Given an array numbers of size n storing n different integers which fall within the range [0, n], implement a function to identify the missing element in the array. All numbers except one are present in the array. Find the missing number.

Examples:
- [1,3,0] => 2
- [1] => 0
- [3,0,4,2,1] => 5

Constraints:
- 1 <= n <= 10,000
- 0 <= numbers[i] <= n`,
		cardSummary: "Find the single missing integer in [0..n] from an array of n distinct values.",
		approach: "Compute expected sum of 0..n as n*(n+1)/2, subtract the actual sum of the array. The difference is the missing number.",
		complexity: "Time: O(n), Space: O(1).",
	},
	{
		id: "blind-maximum-product-in-contiguous-array",
		questionNumber: 4,
		path: "maximum-product-in-contiguous-array",
		title: "Maximum Product in Contiguous Array",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: `Given an array of integers numbers, determine the subarray that has the highest product and return that product.

A subarray is a contiguous segment of an array where all elements are taken from consecutive indices, preserving their order.

Examples:
- [1,2,-3,5,1] => 5 (subarray [5,1])
- [9] => 9
- [1,2,0,-1,8,-4] => 32 (subarray [-1,8,-4])

Constraints: 1 <= numbers.length <= 1000, -10 <= numbers[i] <= 10`,
		cardSummary: "Find the maximum product of any contiguous subarray using DP with max/min tracking.",
		approach:
			"Track both max and min product ending at each index. A negative min × negative can become the new max. At each step: maxEnding = max(n, maxEnding*n, minEnding*n), minEnding = min(n, maxEnding*n, minEnding*n).",
		complexity: "Time: O(n), Space: O(1).",
	},
	{
		id: "blind-maximum-sum-in-contiguous-array",
		questionNumber: 5,
		path: "maximum-sum-in-contiguous-array",
		title: "Maximum Sum in Contiguous Array",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: `Given an array of integers numbers, determine the subarray that has the highest sum and return that sum.

A subarray is a contiguous segment of an array where all elements are taken from consecutive indices, preserving their order.

Examples:
- [-1,5,-3,9,-11] => 11 (subarray [5,-3,9])
- [9] => 9
- [1,2,3,4] => 10 (subarray [1,2,3,4])

Constraints: 1 <= numbers.length <= 10,000, -10,000 <= numbers[i] <= 10,000`,
		cardSummary: "Find the maximum sum of any contiguous subarray using Kadane's algorithm.",
		approach:
			"Kadane's algorithm: at each index, maxEnding = max(n, maxEnding + n). Either extend the current subarray or start fresh. Track globalMax.",
		complexity: "Time: O(n), Space: O(1).",
	},
	{
		id: "blind-most-common-elements",
		questionNumber: 6,
		path: "most-common-elements",
		title: "Most Common Elements",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: `Given an array of integers numbers and a number k, find the k most frequent numbers in the array. Here, k represents the number of elements that should be returned, which are the ones that appear the most frequently. The order of the result does not matter.

Examples:
- [4,4,4,6,6,5,5,5], k=2 => [4,5]
- [7,7,7,8,8,9,9,9], k=3 => [7,9,8]
- [10,10,10,10,10], k=1 => [10]

Constraints:
- 1 <= numbers.length <= 1000
- -10,000 <= numbers[i] <= 10,000
- 1 <= k <= Number of unique elements in numbers
- The solution is guaranteed to have a unique result`,
		cardSummary: "Find the k most frequent numbers in an array using a frequency map and sort.",
		approach:
			"Build a frequency map in one pass (Map<number, count>). Sort entries by count descending (with value as tiebreaker for deterministic output). Return the first k numbers.",
		complexity: "Time: O(n log n) for sort, Space: O(n) for the frequency map.",
	},
	{
		id: "blind-array-product-excluding-current",
		questionNumber: 7,
		path: "array-product-excluding-current",
		title: "Array Product Excluding Current",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: `Given an array of integers numbers, return a new array result where each element result[i] represents the product of all the elements in numbers except for numbers[i]. Division is prohibited.`,
		cardSummary: "Prefix × suffix products in two passes, no division.",
		approach:
			"Build result[i] as (product of elements left of i) × (product of elements right of i). First pass: fill result with left products. Second pass: multiply by right products. O(n) time, O(1) extra space (output excluded).",
		complexity: "Time: O(n), Space: O(1) extra (output array is required).",
	},
	{
		id: "blind-end-of-array-reachable",
		questionNumber: 8,
		path: "end-of-array-reachable",
		title: "End of Array Reachable",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.AlgoVisualizer],
		status: QuestionStatus.Done,
		summary: "Determine if you can reach the last index from the first, where each element is the max jump length.",
		cardSummary: "Greedy: track maxReach; return true when maxReach >= lastIndex.",
		approach:
			"Greedy: maintain maxReach (furthest index reachable so far). For each i, if i > maxReach return false. Update maxReach = max(maxReach, i + numbers[i]). Return true when maxReach >= lastIndex.",
		complexity: "Time: O(n), Space: O(1).",
	},
	{
		id: "blind-find-element-in-rotated-array",
		questionNumber: 9,
		path: "find-element-in-rotated-array",
		title: "Find Element in Rotated Array",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.InProgress,
		summary: "TODO: Solve Find Element in Rotated Array.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-smallest-element-in-rotated-sorted-array",
		questionNumber: 10,
		path: "smallest-element-in-rotated-sorted-array",
		title: "Smallest element in rotated sorted array",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.InProgress,
		summary: "TODO: Solve Smallest element in rotated sorted array.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-bst-kth-smallest-element",
		questionNumber: 11,
		path: "binary-search-tree-kth-smallest-element",
		title: "Binary Search Tree Kth Smallest Element",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Search Tree Kth Smallest Element.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-bst-lowest-common-ancestor",
		questionNumber: 12,
		path: "binary-search-tree-lowest-common-ancestor",
		title: "Binary Search Tree Lowest Common Ancestor",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Search Tree Lowest Common Ancestor.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-validate-binary-search-tree",
		questionNumber: 13,
		path: "validate-binary-search-tree",
		title: "Validate Binary Search Tree",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Validate Binary Search Tree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-binary-tree-equal",
		questionNumber: 14,
		path: "binary-tree-equal",
		title: "Binary Tree Equal",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Tree Equal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-flip-binary-tree",
		questionNumber: 15,
		path: "flip-binary-tree",
		title: "Flip Binary Tree",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Flip Binary Tree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-binary-tree-level-order-traversal",
		questionNumber: 16,
		path: "binary-tree-level-order-traversal",
		title: "Binary Tree Level Order Traversal",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Tree Level Order Traversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-binary-tree-maximum-depth",
		questionNumber: 17,
		path: "binary-tree-maximum-depth",
		title: "Binary Tree Maximum Depth",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Tree Maximum Depth.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-binary-tree-maximum-total-path",
		questionNumber: 18,
		path: "binary-tree-maximum-total-path",
		title: "Binary Tree Maximum Total Path",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Tree Maximum Total Path.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-binary-tree-rebuild-preorder-inorder",
		questionNumber: 19,
		path: "binary-tree-rebuilding-from-preorder-and-inorder-traversals",
		title: "Binary Tree Rebuilding from Preorder and Inorder Traversals",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Tree Rebuilding from Preorder and Inorder Traversals.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-binary-tree-serialization-deserialization",
		questionNumber: 20,
		path: "binary-tree-serialization-and-deserialization",
		title: "Binary Tree Serialization and Deserialization",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Tree Serialization and Deserialization.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-binary-tree-subtree",
		questionNumber: 21,
		path: "binary-tree-subtree",
		title: "Binary Tree Subtree",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Binary Tree Subtree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-bit-counting",
		questionNumber: 22,
		path: "bit-counting",
		title: "Bit Counting",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Bit Counting.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-bit-reversal",
		questionNumber: 23,
		path: "bit-reversal",
		title: "Bit Reversal",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Bit Reversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-minimum-coins-for-change",
		questionNumber: 24,
		path: "minimum-coins-for-change",
		title: "Minimum Coins for Change",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Minimum Coins for Change.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-combinations-for-target-sum",
		questionNumber: 25,
		path: "combinations-for-target-sum",
		title: "Combinations for Target Sum",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Combinations for Target Sum.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-count-set-bits-binary-number",
		questionNumber: 26,
		path: "count-set-bits-in-a-binary-number",
		title: "Count Set Bits in a Binary Number",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Count Set Bits in a Binary Number.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-course-dependency",
		questionNumber: 27,
		path: "course-dependency",
		title: "Course Dependency",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Course Dependency.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-disjoint-intervals",
		questionNumber: 28,
		path: "disjoint-intervals",
		title: "Disjoint Intervals",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Disjoint Intervals.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-extraterrestrial-language",
		questionNumber: 29,
		path: "extraterrestrial-language",
		title: "Extraterrestrial Language",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Extraterrestrial Language.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-graph-clone",
		questionNumber: 30,
		path: "graph-clone",
		title: "Graph Clone",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Graph Clone.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-graph-count-connected-components",
		questionNumber: 31,
		path: "graph-count-connected-components",
		title: "Graph Count Connected Components",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Graph Count Connected Components.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-is-the-graph-a-tree",
		questionNumber: 32,
		path: "is-the-graph-a-tree",
		title: "Is the Graph a Tree",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Is the Graph a Tree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-count-islands-in-grid",
		questionNumber: 33,
		path: "count-islands-in-a-grid",
		title: "Count Islands in a Grid",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Count Islands in a Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-distinct-paths-in-grid",
		questionNumber: 34,
		path: "distinct-paths-in-grid",
		title: "Distinct Paths in Grid",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Distinct Paths in Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-find-word-in-grid",
		questionNumber: 35,
		path: "find-word-in-grid",
		title: "Find Word in Grid",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Find Word in Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-find-words-in-grid",
		questionNumber: 36,
		path: "find-words-in-grid",
		title: "Find Words in Grid",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Find Words in Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-merge-overlapping-intervals",
		questionNumber: 37,
		path: "merge-overlapping-intervals",
		title: "Merge Overlapping Intervals",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Merge Overlapping Intervals.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-meeting-calendar",
		questionNumber: 38,
		path: "meeting-calendar",
		title: "Meeting Calendar",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Meeting Calendar.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-merge-new-interval",
		questionNumber: 39,
		path: "merge-new-interval",
		title: "Merge New Interval",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Merge New Interval.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-minimum-meeting-rooms-needed",
		questionNumber: 40,
		path: "minimum-meeting-rooms-needed",
		title: "Minimum Meeting Rooms Needed",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Minimum Meeting Rooms Needed.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-linked-lists-combine-k-sorted",
		questionNumber: 41,
		path: "linked-lists-combine-k-sorted",
		title: "Linked Lists Combine K Sorted",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Linked Lists Combine K Sorted.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-linked-lists-combine-two-sorted",
		questionNumber: 42,
		path: "linked-lists-combine-two-sorted",
		title: "Linked Lists Combine Two Sorted",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Linked Lists Combine Two Sorted.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-delete-nth-node-from-end",
		questionNumber: 43,
		path: "delete-nth-node-from-end-of-linked-list",
		title: "Delete Nth Node from End of Linked List",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Delete Nth Node from End of Linked List.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-linked-list-detect-cycle",
		questionNumber: 44,
		path: "linked-list-detect-cycle",
		title: "Linked List Detect Cycle",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Linked List Detect Cycle.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-rearrange-linked-list",
		questionNumber: 45,
		path: "rearrange-linked-list",
		title: "Rearrange Linked List",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Rearrange Linked List.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-linked-list-reversal",
		questionNumber: 46,
		path: "linked-list-reversal",
		title: "Linked List Reversal",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Linked List Reversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-longest-common-subsequence",
		questionNumber: 47,
		path: "longest-common-subsequence",
		title: "Longest Common Subsequence",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Longest Common Subsequence.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-longest-consecutive-number-sequence",
		questionNumber: 48,
		path: "longest-consecutive-number-sequence",
		title: "Longest Consecutive Number Sequence",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Longest Consecutive Number Sequence.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-longest-increasing-subsequence",
		questionNumber: 49,
		path: "longest-increasing-subsequence",
		title: "Longest Increasing Subsequence",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Longest Increasing Subsequence.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-longest-non-repeating-substring",
		questionNumber: 50,
		path: "longest-non-repeating-substring",
		title: "Longest Non-repeating Substring",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Longest Non-repeating Substring.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-longest-palindromic-substring",
		questionNumber: 51,
		path: "find-the-longest-palindromic-substring",
		title: "Find the Longest Palindromic Substring",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Find the Longest Palindromic Substring.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-longest-repeating-substring-after-replacements",
		questionNumber: 52,
		path: "longest-repeating-substring-after-replacements",
		title: "Longest Repeating Substring After Replacements",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Longest Repeating Substring After Replacements.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-matrix-rotation",
		questionNumber: 53,
		path: "matrix-rotation",
		title: "Matrix Rotation",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Matrix Rotation.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-matrix-spiral-traversal",
		questionNumber: 54,
		path: "matrix-spiral-traversal",
		title: "Matrix Spiral Traversal",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Matrix Spiral Traversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-matrix-zeroing",
		questionNumber: 55,
		path: "matrix-zeroing",
		title: "Matrix Zeroing",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Matrix Zeroing.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-maximum-water-trapped-between-walls",
		questionNumber: 56,
		path: "maximum-water-trapped-between-walls",
		title: "Maximum Water Trapped Between Walls",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Maximum Water Trapped Between Walls.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-neighborhood-theft",
		questionNumber: 57,
		path: "neighborhood-theft",
		title: "Neighborhood Theft",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Neighborhood Theft.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-neighborhood-theft-circular",
		questionNumber: 58,
		path: "neighborhood-theft-circular",
		title: "Neighborhood Theft (Circular)",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Neighborhood Theft (Circular).",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-number-stream-median",
		questionNumber: 59,
		path: "number-stream-median",
		title: "Number Stream Median",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Number Stream Median.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-ocean-flow",
		questionNumber: 60,
		path: "ocean-flow",
		title: "Ocean Flow",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Ocean Flow.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-optimal-stock-trading",
		questionNumber: 61,
		path: "optimal-stock-trading",
		title: "Optimal Stock Trading",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Optimal Stock Trading.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-pair-sum",
		questionNumber: 62,
		path: "pair-sum",
		title: "Pair sum",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Pair sum.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-staircase-climbing-combinations",
		questionNumber: 63,
		path: "staircase-climbing-combinations",
		title: "Staircase Climbing Combinations",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Staircase Climbing Combinations.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-string-anagram",
		questionNumber: 64,
		path: "string-anagram",
		title: "String Anagram",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve String Anagram.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-string-anagram-groups",
		questionNumber: 65,
		path: "string-anagram-groups",
		title: "String Anagram Groups",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve String Anagram Groups.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-decode-message",
		questionNumber: 66,
		path: "decode-message",
		title: "Decode Message",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Decode Message.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-string-palindrome",
		questionNumber: 67,
		path: "string-palindrome",
		title: "String Palindrome",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve String Palindrome.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-palindromic-substrings",
		questionNumber: 68,
		path: "palindromic-substrings",
		title: "Palindromic Substrings",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Palindromic Substrings.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-segment-words",
		questionNumber: 69,
		path: "segment-words",
		title: "Segment Words",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Segment Words.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-shortest-substring-containing-characters",
		questionNumber: 70,
		path: "shortest-substring-containing-characters",
		title: "Shortest Substring Containing Characters",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Shortest Substring Containing Characters.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-sum-without-addition",
		questionNumber: 71,
		path: "sum-without-addition",
		title: "Sum Without Addition",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Sum Without Addition.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-task-coordination",
		questionNumber: 72,
		path: "task-coordination",
		title: "Task Coordination",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Task Coordination.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-trie-prefix-tree",
		questionNumber: 73,
		path: "trie-prefix-tree",
		title: "Trie (Prefix Tree)",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Trie (Prefix Tree).",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-triplet-sum",
		questionNumber: 74,
		path: "triplet-sum",
		title: "Triplet Sum",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Triplet Sum.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "blind-word-finder",
		questionNumber: 75,
		path: "word-finder",
		title: "Word Finder",
		track: Track.Blind75,
		category: "Algorithmic coding",
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Word Finder.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
	},
];
