import type { Question } from "./types";

export const BLIND75_QUESTIONS: Question[] = [
	{
		id: "blind-balanced-brackets",
		questionNumber: 1,
		slug: "balanced-brackets",
		title: "Balanced Brackets",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/blind75/questions/algo/array-balanced-brackets",
		solutionType: "algo_visualizer",
		status: "done",
		summary: `Given a string containing only bracket characters, determine whether it is properly balanced.

A string is balanced when:
1. Every opening bracket is closed by the same type.
2. Brackets close in the correct order.
3. Any nested subset inside a matched pair is also balanced.

Constraints:
- 1 <= str.length <= 1000
- Characters are limited to (, ), {, }, [ and ].`,
		cardSummary:
			"Determine whether a bracket string is properly balanced under matching/order rules.",
		approach:
			"Validate constraints first (length and supported tokens). Then scan left-to-right with a stack: push opening brackets; for closing brackets, ensure the top is the matching opener before popping. Return false on any mismatch and true only if the stack is empty at the end.",
		complexity: "Time: O(n), Space: O(n).",
		tags: ["stack", "parsing", "strings"],
	},
	{
		id: "blind-find-duplicates-in-array",
		questionNumber: 2,
		slug: "find-duplicates-in-array",
		title: "Find Duplicates in Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/blind75/questions/algo/array-find-duplicate",
		solutionType: "algo_visualizer",
		status: "done",
		summary: `Given an array of integers numbers, determine whether the array contains any duplicate values. A duplicate is defined as any number that appears more than once in the array.

Examples:
- [5, 7, 1, 3] => false
- [10, 7, 0, 0, 9] => true
- [3, 2, 6, 5, 0, 3, 10, 3, 10, 5] => true

Constraints:
- 1 <= numbers.length <= 10,000
- -1,000,000 <= numbers[i] <= 1,000,000`,
		cardSummary:
			"Detect whether any integer appears more than once in an array.",
		approach:
			"Scan the array once while storing seen values in a Set. For each number, return true immediately if it is already in the Set; otherwise add it and continue. If the loop finishes, every value was unique so return false.",
		complexity: "Time: O(n), Space: O(n).",
		tags: ["arrays", "hash-set", "deduplication"],
	},
	{
		id: "blind-find-missing-number-in-sequence",
		questionNumber: 3,
		slug: "find-missing-number-in-sequence",
		title: "Find Missing Number in Sequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Find Missing Number in Sequence.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-maximum-product-in-contiguous-array",
		questionNumber: 4,
		slug: "maximum-product-in-contiguous-array",
		title: "Maximum Product in Contiguous Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Maximum Product in Contiguous Array.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-maximum-sum-in-contiguous-array",
		questionNumber: 5,
		slug: "maximum-sum-in-contiguous-array",
		title: "Maximum Sum in Contiguous Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Maximum Sum in Contiguous Array.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-most-common-elements",
		questionNumber: 6,
		slug: "most-common-elements",
		title: "Most Common Elements",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Most Common Elements.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-array-product-excluding-current",
		questionNumber: 7,
		slug: "array-product-excluding-current",
		title: "Array Product Excluding Current",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Array Product Excluding Current.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-end-of-array-reachable",
		questionNumber: 8,
		slug: "end-of-array-reachable",
		title: "End of Array Reachable",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve End of Array Reachable.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-find-element-in-rotated-array",
		questionNumber: 9,
		slug: "find-element-in-rotated-array",
		title: "Find Element in Rotated Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Find Element in Rotated Array.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-smallest-element-in-rotated-sorted-array",
		questionNumber: 10,
		slug: "smallest-element-in-rotated-sorted-array",
		title: "Smallest element in rotated sorted array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Smallest element in rotated sorted array.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bst-kth-smallest-element",
		questionNumber: 11,
		slug: "binary-search-tree-kth-smallest-element",
		title: "Binary Search Tree Kth Smallest Element",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Search Tree Kth Smallest Element.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bst-lowest-common-ancestor",
		questionNumber: 12,
		slug: "binary-search-tree-lowest-common-ancestor",
		title: "Binary Search Tree Lowest Common Ancestor",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Search Tree Lowest Common Ancestor.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-validate-binary-search-tree",
		questionNumber: 13,
		slug: "validate-binary-search-tree",
		title: "Validate Binary Search Tree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Validate Binary Search Tree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-equal",
		questionNumber: 14,
		slug: "binary-tree-equal",
		title: "Binary Tree Equal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Equal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-flip-binary-tree",
		questionNumber: 15,
		slug: "flip-binary-tree",
		title: "Flip Binary Tree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Flip Binary Tree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-level-order-traversal",
		questionNumber: 16,
		slug: "binary-tree-level-order-traversal",
		title: "Binary Tree Level Order Traversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Level Order Traversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-maximum-depth",
		questionNumber: 17,
		slug: "binary-tree-maximum-depth",
		title: "Binary Tree Maximum Depth",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Maximum Depth.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-maximum-total-path",
		questionNumber: 18,
		slug: "binary-tree-maximum-total-path",
		title: "Binary Tree Maximum Total Path",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Maximum Total Path.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-rebuild-preorder-inorder",
		questionNumber: 19,
		slug: "binary-tree-rebuilding-from-preorder-and-inorder-traversals",
		title: "Binary Tree Rebuilding from Preorder and Inorder Traversals",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary:
			"TODO: Solve Binary Tree Rebuilding from Preorder and Inorder Traversals.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-serialization-deserialization",
		questionNumber: 20,
		slug: "binary-tree-serialization-and-deserialization",
		title: "Binary Tree Serialization and Deserialization",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Serialization and Deserialization.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-subtree",
		questionNumber: 21,
		slug: "binary-tree-subtree",
		title: "Binary Tree Subtree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Subtree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bit-counting",
		questionNumber: 22,
		slug: "bit-counting",
		title: "Bit Counting",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Bit Counting.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bit-reversal",
		questionNumber: 23,
		slug: "bit-reversal",
		title: "Bit Reversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Bit Reversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-minimum-coins-for-change",
		questionNumber: 24,
		slug: "minimum-coins-for-change",
		title: "Minimum Coins for Change",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Minimum Coins for Change.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-combinations-for-target-sum",
		questionNumber: 25,
		slug: "combinations-for-target-sum",
		title: "Combinations for Target Sum",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Combinations for Target Sum.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-count-set-bits-binary-number",
		questionNumber: 26,
		slug: "count-set-bits-in-a-binary-number",
		title: "Count Set Bits in a Binary Number",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Count Set Bits in a Binary Number.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-course-dependency",
		questionNumber: 27,
		slug: "course-dependency",
		title: "Course Dependency",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Course Dependency.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-disjoint-intervals",
		questionNumber: 28,
		slug: "disjoint-intervals",
		title: "Disjoint Intervals",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Disjoint Intervals.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-extraterrestrial-language",
		questionNumber: 29,
		slug: "extraterrestrial-language",
		title: "Extraterrestrial Language",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Extraterrestrial Language.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-graph-clone",
		questionNumber: 30,
		slug: "graph-clone",
		title: "Graph Clone",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Graph Clone.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-graph-count-connected-components",
		questionNumber: 31,
		slug: "graph-count-connected-components",
		title: "Graph Count Connected Components",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Graph Count Connected Components.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-is-the-graph-a-tree",
		questionNumber: 32,
		slug: "is-the-graph-a-tree",
		title: "Is the Graph a Tree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Is the Graph a Tree.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-count-islands-in-grid",
		questionNumber: 33,
		slug: "count-islands-in-a-grid",
		title: "Count Islands in a Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Count Islands in a Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-distinct-paths-in-grid",
		questionNumber: 34,
		slug: "distinct-paths-in-grid",
		title: "Distinct Paths in Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Distinct Paths in Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-find-word-in-grid",
		questionNumber: 35,
		slug: "find-word-in-grid",
		title: "Find Word in Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Find Word in Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-find-words-in-grid",
		questionNumber: 36,
		slug: "find-words-in-grid",
		title: "Find Words in Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Find Words in Grid.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-merge-overlapping-intervals",
		questionNumber: 37,
		slug: "merge-overlapping-intervals",
		title: "Merge Overlapping Intervals",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Merge Overlapping Intervals.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-meeting-calendar",
		questionNumber: 38,
		slug: "meeting-calendar",
		title: "Meeting Calendar",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Meeting Calendar.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-merge-new-interval",
		questionNumber: 39,
		slug: "merge-new-interval",
		title: "Merge New Interval",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Merge New Interval.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-minimum-meeting-rooms-needed",
		questionNumber: 40,
		slug: "minimum-meeting-rooms-needed",
		title: "Minimum Meeting Rooms Needed",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Minimum Meeting Rooms Needed.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-lists-combine-k-sorted",
		questionNumber: 41,
		slug: "linked-lists-combine-k-sorted",
		title: "Linked Lists Combine K Sorted",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Linked Lists Combine K Sorted.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-lists-combine-two-sorted",
		questionNumber: 42,
		slug: "linked-lists-combine-two-sorted",
		title: "Linked Lists Combine Two Sorted",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Linked Lists Combine Two Sorted.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-delete-nth-node-from-end",
		questionNumber: 43,
		slug: "delete-nth-node-from-end-of-linked-list",
		title: "Delete Nth Node from End of Linked List",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Delete Nth Node from End of Linked List.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-list-detect-cycle",
		questionNumber: 44,
		slug: "linked-list-detect-cycle",
		title: "Linked List Detect Cycle",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Linked List Detect Cycle.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-rearrange-linked-list",
		questionNumber: 45,
		slug: "rearrange-linked-list",
		title: "Rearrange Linked List",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Rearrange Linked List.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-list-reversal",
		questionNumber: 46,
		slug: "linked-list-reversal",
		title: "Linked List Reversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Linked List Reversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-common-subsequence",
		questionNumber: 47,
		slug: "longest-common-subsequence",
		title: "Longest Common Subsequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Longest Common Subsequence.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-consecutive-number-sequence",
		questionNumber: 48,
		slug: "longest-consecutive-number-sequence",
		title: "Longest Consecutive Number Sequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Longest Consecutive Number Sequence.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-increasing-subsequence",
		questionNumber: 49,
		slug: "longest-increasing-subsequence",
		title: "Longest Increasing Subsequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Longest Increasing Subsequence.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-non-repeating-substring",
		questionNumber: 50,
		slug: "longest-non-repeating-substring",
		title: "Longest Non-repeating Substring",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Longest Non-repeating Substring.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-palindromic-substring",
		questionNumber: 51,
		slug: "find-the-longest-palindromic-substring",
		title: "Find the Longest Palindromic Substring",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Find the Longest Palindromic Substring.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-repeating-substring-after-replacements",
		questionNumber: 52,
		slug: "longest-repeating-substring-after-replacements",
		title: "Longest Repeating Substring After Replacements",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Longest Repeating Substring After Replacements.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-matrix-rotation",
		questionNumber: 53,
		slug: "matrix-rotation",
		title: "Matrix Rotation",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Matrix Rotation.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-matrix-spiral-traversal",
		questionNumber: 54,
		slug: "matrix-spiral-traversal",
		title: "Matrix Spiral Traversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Matrix Spiral Traversal.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-matrix-zeroing",
		questionNumber: 55,
		slug: "matrix-zeroing",
		title: "Matrix Zeroing",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Matrix Zeroing.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-maximum-water-trapped-between-walls",
		questionNumber: 56,
		slug: "maximum-water-trapped-between-walls",
		title: "Maximum Water Trapped Between Walls",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Maximum Water Trapped Between Walls.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-neighborhood-theft",
		questionNumber: 57,
		slug: "neighborhood-theft",
		title: "Neighborhood Theft",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Neighborhood Theft.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-neighborhood-theft-circular",
		questionNumber: 58,
		slug: "neighborhood-theft-circular",
		title: "Neighborhood Theft (Circular)",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Neighborhood Theft (Circular).",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-number-stream-median",
		questionNumber: 59,
		slug: "number-stream-median",
		title: "Number Stream Median",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Number Stream Median.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-ocean-flow",
		questionNumber: 60,
		slug: "ocean-flow",
		title: "Ocean Flow",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Ocean Flow.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-optimal-stock-trading",
		questionNumber: 61,
		slug: "optimal-stock-trading",
		title: "Optimal Stock Trading",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Optimal Stock Trading.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-pair-sum",
		questionNumber: 62,
		slug: "pair-sum",
		title: "Pair sum",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Pair sum.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-staircase-climbing-combinations",
		questionNumber: 63,
		slug: "staircase-climbing-combinations",
		title: "Staircase Climbing Combinations",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Staircase Climbing Combinations.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-string-anagram",
		questionNumber: 64,
		slug: "string-anagram",
		title: "String Anagram",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve String Anagram.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-string-anagram-groups",
		questionNumber: 65,
		slug: "string-anagram-groups",
		title: "String Anagram Groups",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve String Anagram Groups.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-decode-message",
		questionNumber: 66,
		slug: "decode-message",
		title: "Decode Message",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Decode Message.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-string-palindrome",
		questionNumber: 67,
		slug: "string-palindrome",
		title: "String Palindrome",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve String Palindrome.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-palindromic-substrings",
		questionNumber: 68,
		slug: "palindromic-substrings",
		title: "Palindromic Substrings",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Palindromic Substrings.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-segment-words",
		questionNumber: 69,
		slug: "segment-words",
		title: "Segment Words",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Segment Words.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-shortest-substring-containing-characters",
		questionNumber: 70,
		slug: "shortest-substring-containing-characters",
		title: "Shortest Substring Containing Characters",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Shortest Substring Containing Characters.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-sum-without-addition",
		questionNumber: 71,
		slug: "sum-without-addition",
		title: "Sum Without Addition",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Sum Without Addition.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-task-coordination",
		questionNumber: 72,
		slug: "task-coordination",
		title: "Task Coordination",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Task Coordination.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-trie-prefix-tree",
		questionNumber: 73,
		slug: "trie-prefix-tree",
		title: "Trie (Prefix Tree)",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Trie (Prefix Tree).",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-triplet-sum",
		questionNumber: 74,
		slug: "triplet-sum",
		title: "Triplet Sum",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Triplet Sum.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-word-finder",
		questionNumber: 75,
		slug: "word-finder",
		title: "Word Finder",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code_and_tests",
		status: "todo",
		summary: "TODO: Solve Word Finder.",
		cardSummary: "TODO: Add concise card summary.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
];
