import { Category, Difficulty, QuestionStatus, SolutionType, Track, type Question } from "./types";

// This manifest intentionally includes many TODO entries so challenge work can
// be completed incrementally while preserving the planned track ordering.
export const GFE75_QUESTIONS: Question[] = [
	{
		id: "gfe-debounce",
		questionNumber: 1,
		path: "debounce",
		title: "Debounce",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/study/gfe75/questions/javascript/debounce",
		solutionTypes: [SolutionType.AlgoVisualizer, SolutionType.TimelineVisualizer],
		status: QuestionStatus.Done,
		summary: `Debouncing controls how often a function is allowed to execute over time.

When a function is debounced with a wait time of X milliseconds, it executes only after X milliseconds have passed since the last invocation.

A common real-world example is an elevator "Door open" button: only after no one presses it for a while does the door close.

Implement a debounce function that accepts a callback and a wait duration, and returns a debounced version of that callback.`,
		cardSummary:
			"Implement a function to limit how many times a function can be executed by delaying the execution of the function until after a specified time after its last execution attempt",
		approach:
			"Store a timeout id in closure state. On each invocation, clear the previous timeout and schedule a new one for `wait` ms. Execute the callback only in that latest timeout so rapid calls collapse into a single trailing execution.",
		complexity: "Time: O(1) per call, Space: O(1).",
	},
	{
		id: "gfe-array-prototype-reduce",
		questionNumber: 2,
		path: "array-prototype-reduce",
		title: "Array.prototype.reduce",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.InProgress,
		summary: "TODO: Solve Array.prototype.reduce.",
		cardSummary: "Implement the Array.prototype.reduce() method",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-classnames",
		questionNumber: 3,
		path: "classnames",
		title: "Classnames",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Classnames.",
		cardSummary: "Implement a function that conditionally joins CSS class names together",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-flatten",
		questionNumber: 4,
		path: "flatten",
		title: "Flatten",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Flatten.",
		cardSummary: "Implement a function that recursively flattens an array into a single level deep",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-throttle",
		questionNumber: 5,
		path: "throttle",
		title: "Throttle",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.AlgoVisualizer, SolutionType.TimelineVisualizer],
		status: QuestionStatus.Done,
		summary: `Throttling controls how often a function can be invoked over time. When throttled with a wait of X ms, the callback executes immediately on the first call and cannot be invoked again until X ms have passed.

Example: throttle(increment, 100) — at t=0 call executes (i=1), at t=50 call is skipped, at t=101 call executes (i=2).`,
		cardSummary: "Implement a function to limit invocations to at most once per wait period, executing immediately.",
		approach:
			"Track lastExecutedAt. On each invocation: if lastExecutedAt is null or (now - lastExecutedAt) >= waitMs, execute callback and set lastExecutedAt = now; else skip.",
		complexity: "Time: O(1) per call, Space: O(1).",
	},
	{
		id: "gfe-todo-list",
		questionNumber: 6,
		path: "todo-list",
		title: "Todo List",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/study/gfe75/questions/user-interface/todo-list",
		solutionTypes: [SolutionType.UiDemo, SolutionType.GraphQL, SolutionType.Redux],
		status: QuestionStatus.Done,
		cardSummary: "Build a Todo list that lets users add new tasks and delete existing tasks",
		summary: `You're given existing HTML for a Todo List app.

Implement the following:
1. Add new tasks on clicking the "Submit" button.
2. Clear the input field upon successful addition.
3. Remove tasks on clicking the "Delete" button.

Notes:
- Focus on functionality, not styling; no custom CSS is required.
- Markup changes are allowed (ids, data attributes, tags) as long as visuals remain the same.
- User experience improvements are bonus interview credit.`,
		approach: `Use GraphQL + RTK Query for tasks. Data flows through GraphQL as if from a DB; resolvers use in-memory storage (swap for a real DB when needed).

Implementation details:
- TodoDemo uses useTasksQuery, useAddTaskMutation, useRemoveTaskMutation, useClearTasksMutation.
- Keep the task input controlled in TodoDemo; clear after successful adds and keep autoFocus for fast entry.
- Provide guardrails with disabled empty-submit and disabled clear-all when there are no tasks.`,
		complexity: "Time: O(n) for delete, Space: O(n).",
	},
	{
		id: "gfe-contact-form",
		questionNumber: 7,
		path: "contact-form",
		title: "Contact Form",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo, SolutionType.API],
		status: QuestionStatus.Done,
		summary: `Build a basic "Contact Us" form, commonly seen on marketing websites for visitors to ask questions or provide feedback.

Requirements:
- Name field, Email field, Message field (textarea), Submit button with text "Send"
- Form submits via native HTML POST (no JavaScript)
- POST to https://questions.greatfrontend.com/api/questions/contact-form with body fields: name, email, message`,
		cardSummary: "Build a contact form which submits user feedback and contact details to a back end API",
		approach: `Client: contact-form-demo.tsx uses onSubmit with preventDefault, reads FormData, and fetch POSTs JSON to /api/contact-form. On response, shows alert and resets form. Next.js App Router maps that URL to route.ts. Server: route.ts parses and validates the body, proxies the request to the Great Frontend API, and forwards the response. The proxy avoids CORS: the browser only talks to same-origin /api/contact-form; the server calls the external API (no CORS on server-to-server).`,
		complexity: "O(1) form submission.",
	},
	{
		id: "gfe-holy-grail",
		questionNumber: 8,
		path: "holy-grail",
		title: "Holy Grail",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.InProgress,
		summary: "TODO: Solve Holy Grail.",
		cardSummary: "Build the famous holy grail layout consisting of a header, 3 columns, and a footer",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-tabs",
		questionNumber: 9,
		path: "tabs",
		title: "Tabs",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Tabs.",
		cardSummary: "Build a tabs component that displays a list of tab elements and one associated panel of content at a time",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-job-board",
		questionNumber: 10,
		path: "job-board",
		title: "Job Board",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Job Board.",
		cardSummary: "Build a job board that displays the latest job postings from Hacker News",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-accordion",
		questionNumber: 11,
		path: "accordion",
		title: "Accordion",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Accordion.",
		cardSummary:
			"Build an accordion component that a displays a list of vertically stacked sections with each containing a title and content snippet",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-news-feed",
		questionNumber: 12,
		path: "news-feed-facebook",
		title: "News Feed (Facebook)",
		track: Track.Gfe75,
		category: Category.SystemDesign,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/study/gfe75/questions/system-design/news-feed-facebook",
		solutionTypes: [SolutionType.UiDemo, SolutionType.GraphQL, SolutionType.Redux],
		status: QuestionStatus.Done,
		summary: `Design a news feed UI that supports browsing posts, reacting to posts, and creating/publishing posts.

Core scope:
- Feed list with infinite scrolling pagination.
- Post interactions (like/react).
- Post composer for new posts.

Comments and sharing are out of core scope.`,
		cardSummary: "Design a Facebook-style feed with infinite scroll, reactions, and post creation.",
		approach: `Architecture and boundaries:
- The runnable solution keeps orchestration in one controller-style component (NewsFeedDemo) and uses GraphQL + RTK Query for data.
- In-memory resolvers handle feedPage, createPost, reactToPost; data flows through GraphQL as if from a DB (swap for a real DB when needed).

Client state model:
- Feed state tracks posts, nextCursor, loading, submitting, and error, plus composer fields for post body/image URL.
- A loadingRef guard prevents duplicate page fetches when the observer callback fires repeatedly during layout/scroll churn.

Pagination strategy (cursor-based):
- The feed API shape is fetchFeedPage(cursor) -> { posts, nextCursor } with fixed PAGE_SIZE.
- Cursor is the last visible post id from the previous page; the next page starts strictly after that id.
- Cursor pagination is chosen over offset/page because feeds are time-ordered and frequently mutated at the top, where offset drift causes duplicates or skipped results.

Infinite scrolling behavior:
- First page loads on mount with cursor = null.
- IntersectionObserver watches a bottom sentinel and triggers the next fetch when it intersects.
- rootMargin: "100% 0px" prefetches roughly one viewport early to reduce visible loading gaps.
- Appends include id-based deduplication so overlap/race conditions do not render duplicate posts.

Post composer flow:
- Composer supports text-only, image-only, or mixed posts; submit is disabled when both fields are empty.
- On successful create, the new post is prepended and the form is cleared.
- Prepending mirrors real feeds where freshly created content should appear immediately at the top.

Reaction flow (optimistic updates):
- applyReactionTransition handles reaction toggle/switch rules locally (remove old reaction count, add new reaction count, update reactionByMe).
- UI applies the transition immediately, then persists asynchronously for better perceived responsiveness.
- If persistence fails, the previous reaction state is restored and an inline error is shown.

Accessibility, i18n, and theming:
- Feed semantics use role="feed" on the container and role="article" with aria-labelledby per post.
- Reaction buttons expose aria-pressed to reflect active state for assistive tech.
- Relative time uses Intl.RelativeTimeFormat for locale-aware labels.
- Styling uses design tokens (--card-bg, --input-bg, etc.) so the same UI works in light and dark themes.

Interview-ready extensions:
- Swap mock API helpers for a query/mutation layer (React Query/Relay) with request cancellation and retries.
- Add list virtualization for very long sessions and stale-feed refresh prompts for old tabs.
- Add live updates (WebSocket/SSE), plus optimistic comments/shares using the same mutation pattern.`,
		complexity: "Time: O(n) render, per-page fetch O(pageSize).",
	},
	{
		id: "gfe-autocomplete",
		questionNumber: 13,
		path: "autocomplete",
		title: "Autocomplete",
		track: Track.Gfe75,
		category: Category.SystemDesign,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.InProgress,
		summary: "TODO: Solve Autocomplete.",
		cardSummary: "Design an autocomplete component seen on Google and Facebook search",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-type-utilities-ii",
		questionNumber: 14,
		path: "type-utilities-ii",
		title: "Type Utilities II",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Type Utilities II.",
		cardSummary: "Implement utilities to determine non-primitive variable types in JavaScript",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-promise-all",
		questionNumber: 15,
		path: "promise-all",
		title: "Promise.all",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Promise.all.",
		cardSummary:
			"Implement the Promise.all() function that resolves to an array of results if all the input elements are resolved or rejects otherwise",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-data-merging",
		questionNumber: 16,
		path: "data-merging",
		title: "Data Merging",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Data Merging.",
		cardSummary: "Implement a function to merge rows of data from the same user",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-deep-clone",
		questionNumber: 17,
		path: "deep-clone",
		title: "Deep Clone",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Deep Clone.",
		cardSummary: "Implement a function that performs a deep copy of a value",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-event-emitter",
		questionNumber: 18,
		path: "event-emitter",
		title: "Event Emitter",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Event Emitter.",
		cardSummary: "Implement a class that can subscribe to and emit events that trigger attached callback functions",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-get-elements-by-style",
		questionNumber: 19,
		path: "get-elements-by-style",
		title: "getElementsByStyle",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve getElementsByStyle.",
		cardSummary: "Implement a function to get all DOM elements that are rendered using the specified style",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-function-prototype-call",
		questionNumber: 20,
		path: "function-prototype-call",
		title: "Function.prototype.call",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Function.prototype.call.",
		cardSummary: "Implement the Function.prototype.call() function that calls the function with a given `this` value and provided arguments",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-list-format",
		questionNumber: 21,
		path: "list-format",
		title: "List Format",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve List Format.",
		cardSummary: "Implement a function that formats a list of items into a single readable string",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-map-async-limit",
		questionNumber: 22,
		path: "map-async-limit",
		title: "Map Async Limit",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Map Async Limit.",
		cardSummary: "Implement a function that maps an array of items with an asynchronous mapping function while not exceeding the concurrency limit",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-deep-equal",
		questionNumber: 23,
		path: "deep-equal",
		title: "Deep Equal",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Deep Equal.",
		cardSummary: "Implement a function that determines if two values are equal",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-promise-any",
		questionNumber: 24,
		path: "promise-any",
		title: "Promise.any",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Promise.any.",
		cardSummary: "Implement the Promise.any() function that resolves when any of the input elements are resolved",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-deep-omit",
		questionNumber: 25,
		path: "deep-omit",
		title: "Deep Omit",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Deep Omit.",
		cardSummary: "Implement a function that removes specified keys and their corresponding values from an object, including nested objects or arrays",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-promisify",
		questionNumber: 26,
		path: "promisify",
		title: "Promisify",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Promisify.",
		cardSummary:
			"Implement a function that takes a function following the common error-first callback style and returns a version that returns promises",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-memoize",
		questionNumber: 27,
		path: "memoize",
		title: "Memoize",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Memoize.",
		cardSummary: "Implement a function that returns a memoized version of a function which accepts a single argument",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-squash-object",
		questionNumber: 28,
		path: "squash-object",
		title: "Squash Object",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Squash Object.",
		cardSummary: "Implement a function that returns a new object after squashing the input object into a single level of depth",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-get-elements-by-classname",
		questionNumber: 29,
		path: "get-elements-by-classname",
		title: "getElementsByClassName",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve getElementsByClassName.",
		cardSummary: "Implement a function to get all DOM elements that contain the specified classes",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-storage-quiz",
		questionNumber: 30,
		path: "cookie-sessionstorage-localstorage",
		title: "Cookie vs sessionStorage vs localStorage",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/gfe75/questions/quiz/describe-the-difference-between-a-cookie-sessionstorage-and-localstorage",
		solutionTypes: [SolutionType.Writeup, SolutionType.WebStorage],
		status: QuestionStatus.Done,
		summary: "Compare client-side storage options in browsers: cookies, sessionStorage, and localStorage.",
		cardSummary: "Describe the difference between a cookie, `sessionStorage` and `localStorage` in browsers",
		approach:
			"Compare along five axes: initiator, lifetime, request behavior, scope, and security. Emphasize that cookies are automatically included in HTTP requests while Web Storage is not, then map practical use cases: cookie for server session concerns, localStorage for persistent client preferences, sessionStorage for temporary tab-local state.",
		complexity: "Conceptual question.",
	},
	{
		id: "gfe-script-async-defer",
		questionNumber: 31,
		path: "script-async-defer",
		title: "Describe the difference between <script>, <script async> and <script defer>",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/gfe75/questions/quiz/describe-the-difference-between-script-script-async-and-script-defer",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Done,
		summary: "Compare how <script>, <script async>, and <script defer> affect HTML parsing and script execution.",
		cardSummary: "Describe the difference between `<script>`, `<script async>` and `<script defer>`",
		approach:
			"Compare along three axes: parsing behavior (blocking vs parallel), execution order (in-order vs not guaranteed), and DOM dependency. Emphasize that regular script blocks parsing; async downloads in parallel and executes ASAP (order not guaranteed); defer downloads in parallel and executes after DOM is parsed, in order. Map use cases: regular for critical render-blocking scripts, async for independent third-party scripts (analytics, ads), defer for DOM-dependent scripts.",
		complexity: "Conceptual question.",
	},
	{
		id: "gfe-hoisting-concept",
		questionNumber: 32,
		path: "hoisting-concept",
		title: "Explain the concept of hoisting in JavaScript",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.InProgress,
		summary: "TODO: Answer hoisting concept.",
		cardSummary: 'Explain the concept of "hoisting" in JavaScript',
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-let-var-const-differences",
		questionNumber: 33,
		path: "let-var-const-differences",
		title: "Differences between let, var and const",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer let/var/const differences.",
		cardSummary: "What are the differences between JavaScript variables created using `let`, `var` or `const`?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-closure-concept",
		questionNumber: 34,
		path: "closure-concept",
		title: "What is a closure in JavaScript?",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer closure concept.",
		cardSummary: "What is a closure in JavaScript, and how/why would you use one?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-event-bubbling",
		questionNumber: 35,
		path: "event-bubbling",
		title: "Describe event bubbling in JavaScript and browsers",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer event bubbling.",
		cardSummary: "Describe event bubbling in JavaScript and browsers",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-event-delegation",
		questionNumber: 36,
		path: "event-delegation",
		title: "Explain event delegation in JavaScript",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer event delegation.",
		cardSummary: "Explain event delegation in JavaScript",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-null-undefined-undeclared",
		questionNumber: 37,
		path: "null-undefined-undeclared",
		title: "Difference between null, undefined and undeclared",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer null/undefined/undeclared differences.",
		cardSummary: "What's the difference between a JavaScript variable that is: `null`, `undefined` or undeclared?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-commonjs-vs-esm",
		questionNumber: 38,
		path: "commonjs-vs-esm",
		title: "Differences between CommonJS and ES modules",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer CommonJS vs ES modules.",
		cardSummary: "Explain the differences between CommonJS modules and ES modules in JavaScript",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-event-loop",
		questionNumber: 39,
		path: "event-loop",
		title: "What is the event loop in JavaScript runtimes?",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer event loop.",
		cardSummary: "What is the event loop in JavaScript runtimes?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-promises-vs-callbacks",
		questionNumber: 40,
		path: "promises-vs-callbacks",
		title: "Pros and cons of Promises vs callbacks",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer Promises vs callbacks.",
		cardSummary: "What are the pros and cons of using Promises instead of callbacks in JavaScript?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-bfc",
		questionNumber: 41,
		path: "block-formatting-context",
		title: "Describe Block Formatting Context (BFC)",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer Block Formatting Context.",
		cardSummary: "Describe Block Formatting Context (BFC) and how it works.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-z-index-stacking-context",
		questionNumber: 42,
		path: "z-index-stacking-context",
		title: "Describe z-index and stacking context",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer z-index and stacking context.",
		cardSummary: "Describe `z-index` and how stacking context is formed.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-css-selector-matching",
		questionNumber: 43,
		path: "css-selector-matching",
		title: "How browser determines CSS selector matches",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer CSS selector matching.",
		cardSummary: "Explain how a browser determines what elements match a CSS selector.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-box-model",
		questionNumber: 44,
		path: "box-model",
		title: "Explain the box model",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer box model question.",
		cardSummary:
			"Explain your understanding of the box model and how you would tell the browser in CSS to render your layout in different box models.",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-translate-vs-absolute",
		questionNumber: 45,
		path: "translate-vs-absolute",
		title: "translate() vs absolute positioning",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer translate vs absolute positioning.",
		cardSummary: "Is there any reason you'd want to use `translate()` instead of `absolute` positioning, or vice-versa? And why?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-box-sizing-border-box",
		questionNumber: 46,
		path: "box-sizing-border-box",
		title: "What does * { box-sizing: border-box; } do?",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer box-sizing question.",
		cardSummary: "What does `* { box-sizing: border-box; }` do?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-css-display-property",
		questionNumber: 47,
		path: "css-display-property",
		title: "What is the CSS display property?",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer CSS display property question.",
		cardSummary: "What is the CSS `display` property and can you give a few examples of its use?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-position-differences",
		questionNumber: 48,
		path: "position-differences",
		title: "Difference between relative/fixed/absolute/sticky/static",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer positioning differences.",
		cardSummary: "What's the difference between a `relative`, `fixed`, `absolute`, `sticky` and `static`-ally positioned element?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-multilingual-sites",
		questionNumber: 49,
		path: "multilingual-sites",
		title: "Things to watch when building multilingual sites",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer multilingual sites question.",
		cardSummary: "What kind of things must you be wary of when designing or developing for multilingual sites?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-block-inline-inlineblock",
		questionNumber: 50,
		path: "block-inline-inlineblock",
		title: "Difference between block, inline, and inline-block",
		track: Track.Gfe75,
		category: Category.Quiz,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.Writeup],
		status: QuestionStatus.Todo,
		summary: "TODO: Answer block/inline/inline-block differences.",
		cardSummary: "What's the difference between `block`, `inline`, and `inline-block`?",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-curry",
		questionNumber: 51,
		path: "curry",
		title: "Curry",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Curry.",
		cardSummary:
			"Implement a function that transforms a function that takes multiple arguments into a function that can be repeatedly called with only one argument at a time",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-html-serializer",
		questionNumber: 52,
		path: "html-serializer",
		title: "HTML Serializer",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve HTML Serializer.",
		cardSummary: "Implement a function to serialize an object into an HTML string with indentation",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-json-stringify",
		questionNumber: 53,
		path: "json-stringify",
		title: "JSON.stringify",
		track: Track.Gfe75,
		category: Category.JavaScriptFunctions,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.CodeAndTests],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve JSON.stringify.",
		cardSummary: "Implement a function that converts a JavaScript value into a JSON string",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-star-rating",
		questionNumber: 54,
		path: "star-rating",
		title: "Star Rating",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Star Rating.",
		cardSummary:
			"Build a star rating component that shows a row of star icons for users to select the number of filled stars corresponding to the rating",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-image-carousel",
		questionNumber: 55,
		path: "image-carousel",
		title: "Image Carousel",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Image Carousel.",
		cardSummary: "Build an image carousel that displays a sequence of images",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-progress-bars",
		questionNumber: 56,
		path: "progress-bars",
		title: "Progress Bars",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Easy,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Progress Bars.",
		cardSummary: "Build a list of progress bars that fill up gradually when they are added to the page",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-like-button",
		questionNumber: 57,
		path: "like-button",
		title: "Like Button",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Like Button.",
		cardSummary: "Build a Like button that changes appearance based on the states",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-traffic-light",
		questionNumber: 58,
		path: "traffic-light",
		title: "Traffic Light",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Traffic Light.",
		cardSummary: "Build a traffic light where the lights switch from green to yellow to red after predetermined intervals and loop indefinitely",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-digital-clock",
		questionNumber: 59,
		path: "digital-clock",
		title: "Digital Clock",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Digital Clock.",
		cardSummary: "Build a 7-segment digital clock that shows the current time",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-stopwatch",
		questionNumber: 60,
		path: "stopwatch",
		title: "Stopwatch",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Stopwatch.",
		cardSummary: "Build a stopwatch widget that can measure how much time has passed",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-file-explorer",
		questionNumber: 61,
		path: "file-explorer",
		title: "File Explorer",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve File Explorer.",
		cardSummary: "Build a file explorer component to navigate files and directories in a tree-like hierarchical viewer",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-tic-tac-toe",
		questionNumber: 62,
		path: "tic-tac-toe",
		title: "Tic-tac-toe",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Tic-tac-toe.",
		cardSummary: "Build a tic-tac-toe game that is playable by two players",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-transfer-list",
		questionNumber: 63,
		path: "transfer-list",
		title: "Transfer List",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Transfer List.",
		cardSummary: "Build a component that allows transferring of items between two lists",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-nested-checkboxes",
		questionNumber: 64,
		path: "nested-checkboxes",
		title: "Nested Checkboxes",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Hard,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Nested Checkboxes.",
		cardSummary: "Build a nested checkboxes component with parent-child selection logic",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-modal-dialog",
		questionNumber: 65,
		path: "modal-dialog",
		title: "Modal Dialog",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Modal Dialog.",
		cardSummary: "Build a reusable modal dialog component that can be opened and closed",
		approach: "TODO",
		complexity: "TODO",
	},
	{
		id: "gfe-data-table",
		questionNumber: 66,
		path: "data-table",
		title: "Data Table",
		track: Track.Gfe75,
		category: Category.UiCoding,
		difficulty: Difficulty.Medium,
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionTypes: [SolutionType.UiDemo],
		status: QuestionStatus.Todo,
		summary: "TODO: Solve Data Table.",
		cardSummary: "Build a users data table with pagination features",
		approach: "TODO",
		complexity: "TODO",
	},
];
