export type Track = "gfe75" | "blind75";

export type SolutionType =
	| "ui-demo"
	| "algo-visualizer"
	| "code-and-tests"
	| "writeup";

export type QuestionStatus = "todo" | "in-progress" | "done";

export type Question = {
	id: string;
	questionNumber: number;
	slug: string;
	title: string;
	track: Track;
	category: string;
	difficulty: "Easy" | "Medium" | "Hard";
	sourceUrl: string;
	solutionType: SolutionType;
	status: QuestionStatus;
	summary: string;
	approach: string;
	complexity: string;
	tags: string[];
};

// This manifest intentionally includes many TODO entries so challenge work can
// be completed incrementally while preserving the planned track ordering.
export const QUESTIONS: Question[] = [
	{
		id: "gfe-debounce",
		questionNumber: 1,
		slug: "debounce",
		title: "Debounce",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/gfe75/questions/javascript/debounce",
		solutionType: "algo-visualizer",
		status: "done",
		summary: "Delay function execution until calls settle.",
		approach:
			"Use a closure over a timer id. Clear pending timeout on each call and schedule a new one.",
		complexity: "Time: O(1) per call, Space: O(1).",
		tags: ["timers", "closures", "utility"],
	},
	{
		id: "gfe-array-prototype-reduce",
		questionNumber: 2,
		slug: "array-prototype-reduce",
		title: "Array.prototype.reduce",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Array.prototype.reduce.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-classnames",
		questionNumber: 3,
		slug: "classnames",
		title: "Classnames",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Classnames.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-flatten",
		questionNumber: 4,
		slug: "flatten",
		title: "Flatten",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Flatten.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-throttle",
		questionNumber: 5,
		slug: "throttle",
		title: "Throttle",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Throttle.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-todo-list",
		questionNumber: 6,
		slug: "todo-list",
		title: "Todo List",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/gfe75/questions/user-interface/todo-list",
		solutionType: "ui-demo",
		status: "done",
		summary: "Add and delete todo items with controlled input.",
		approach:
			"Store tasks in local component state, append on submit, and remove by id using filter.",
		complexity: "Time: O(n) for delete, Space: O(n).",
		tags: ["forms", "react-state", "list-rendering"],
	},
	{
		id: "gfe-contact-form",
		questionNumber: 7,
		slug: "contact-form",
		title: "Contact Form",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Contact Form.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-holy-grail",
		questionNumber: 8,
		slug: "holy-grail",
		title: "Holy Grail",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Holy Grail.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-tabs",
		questionNumber: 9,
		slug: "tabs",
		title: "Tabs",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Tabs.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-job-board",
		questionNumber: 10,
		slug: "job-board",
		title: "Job Board",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Job Board.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-accordion",
		questionNumber: 11,
		slug: "accordion",
		title: "Accordion",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Accordion.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-news-feed",
		questionNumber: 12,
		slug: "news-feed-facebook",
		title: "News Feed (Facebook)",
		track: "gfe75",
		category: "System design",
		difficulty: "Medium",
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/gfe75/questions/system-design/news-feed-facebook",
		solutionType: "ui-demo",
		status: "done",
		summary:
			"Interactive feed MVP with post creation, infinite scroll, and reactions.",
		approach:
			"Mock cursor pagination with IntersectionObserver, optimistic reaction updates with rollback, and local composer state.",
		complexity: "Time: O(n) render, per-page fetch O(pageSize).",
		tags: ["system-design", "pagination", "performance"],
	},
	{
		id: "gfe-autocomplete",
		questionNumber: 13,
		slug: "autocomplete",
		title: "Autocomplete",
		track: "gfe75",
		category: "System design",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Solve Autocomplete.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-type-utilities-ii",
		questionNumber: 14,
		slug: "type-utilities-ii",
		title: "Type Utilities II",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Type Utilities II.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-promise-all",
		questionNumber: 15,
		slug: "promise-all",
		title: "Promise.all",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Promise.all.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-data-merging",
		questionNumber: 16,
		slug: "data-merging",
		title: "Data Merging",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Data Merging.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-deep-clone",
		questionNumber: 17,
		slug: "deep-clone",
		title: "Deep Clone",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Deep Clone.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-event-emitter",
		questionNumber: 18,
		slug: "event-emitter",
		title: "Event Emitter",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Event Emitter.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-get-elements-by-style",
		questionNumber: 19,
		slug: "get-elements-by-style",
		title: "getElementsByStyle",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve getElementsByStyle.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-function-prototype-call",
		questionNumber: 20,
		slug: "function-prototype-call",
		title: "Function.prototype.call",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Function.prototype.call.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-list-format",
		questionNumber: 21,
		slug: "list-format",
		title: "List Format",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve List Format.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-map-async-limit",
		questionNumber: 22,
		slug: "map-async-limit",
		title: "Map Async Limit",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Map Async Limit.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-deep-equal",
		questionNumber: 23,
		slug: "deep-equal",
		title: "Deep Equal",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Deep Equal.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-promise-any",
		questionNumber: 24,
		slug: "promise-any",
		title: "Promise.any",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Promise.any.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-deep-omit",
		questionNumber: 25,
		slug: "deep-omit",
		title: "Deep Omit",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Deep Omit.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-promisify",
		questionNumber: 26,
		slug: "promisify",
		title: "Promisify",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Promisify.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-memoize",
		questionNumber: 27,
		slug: "memoize",
		title: "Memoize",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Memoize.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-squash-object",
		questionNumber: 28,
		slug: "squash-object",
		title: "Squash Object",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Squash Object.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-get-elements-by-classname",
		questionNumber: 29,
		slug: "get-elements-by-classname",
		title: "getElementsByClassName",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve getElementsByClassName.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-storage-quiz",
		questionNumber: 30,
		slug: "cookie-sessionstorage-localstorage",
		title: "Cookie vs sessionStorage vs localStorage",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/gfe75/questions/quiz/describe-the-difference-between-a-cookie-sessionstorage-and-localstorage",
		solutionType: "ui-demo",
		status: "done",
		summary: "Compare browser storage APIs and cookie behavior.",
		approach:
			"Contrast scope, expiration, capacity, and whether data is sent automatically with requests.",
		complexity: "Conceptual question.",
		tags: ["web-apis", "browser-storage", "security"],
	},
	{
		id: "gfe-script-async-defer",
		questionNumber: 31,
		slug: "script-async-defer",
		title:
			"Describe the difference between <script>, <script async> and <script defer>",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer script loading differences.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-hoisting-concept",
		questionNumber: 32,
		slug: "hoisting-concept",
		title: "Explain the concept of hoisting in JavaScript",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer hoisting concept.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-let-var-const-differences",
		questionNumber: 33,
		slug: "let-var-const-differences",
		title: "Differences between let, var and const",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer let/var/const differences.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-closure-concept",
		questionNumber: 34,
		slug: "closure-concept",
		title: "What is a closure in JavaScript?",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer closure concept.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-event-bubbling",
		questionNumber: 35,
		slug: "event-bubbling",
		title: "Describe event bubbling in JavaScript and browsers",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer event bubbling.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-event-delegation",
		questionNumber: 36,
		slug: "event-delegation",
		title: "Explain event delegation in JavaScript",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer event delegation.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-null-undefined-undeclared",
		questionNumber: 37,
		slug: "null-undefined-undeclared",
		title: "Difference between null, undefined and undeclared",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer null/undefined/undeclared differences.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-commonjs-vs-esm",
		questionNumber: 38,
		slug: "commonjs-vs-esm",
		title: "Differences between CommonJS and ES modules",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer CommonJS vs ES modules.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-event-loop",
		questionNumber: 39,
		slug: "event-loop",
		title: "What is the event loop in JavaScript runtimes?",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer event loop.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-promises-vs-callbacks",
		questionNumber: 40,
		slug: "promises-vs-callbacks",
		title: "Pros and cons of Promises vs callbacks",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer Promises vs callbacks.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-bfc",
		questionNumber: 41,
		slug: "block-formatting-context",
		title: "Describe Block Formatting Context (BFC)",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer Block Formatting Context.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-z-index-stacking-context",
		questionNumber: 42,
		slug: "z-index-stacking-context",
		title: "Describe z-index and stacking context",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer z-index and stacking context.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-css-selector-matching",
		questionNumber: 43,
		slug: "css-selector-matching",
		title: "How browser determines CSS selector matches",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer CSS selector matching.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-box-model",
		questionNumber: 44,
		slug: "box-model",
		title: "Explain the box model",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer box model question.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-translate-vs-absolute",
		questionNumber: 45,
		slug: "translate-vs-absolute",
		title: "translate() vs absolute positioning",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer translate vs absolute positioning.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-box-sizing-border-box",
		questionNumber: 46,
		slug: "box-sizing-border-box",
		title: "What does * { box-sizing: border-box; } do?",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer box-sizing question.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-css-display-property",
		questionNumber: 47,
		slug: "css-display-property",
		title: "What is the CSS display property?",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer CSS display property question.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-position-differences",
		questionNumber: 48,
		slug: "position-differences",
		title: "Difference between relative/fixed/absolute/sticky/static",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer positioning differences.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-multilingual-sites",
		questionNumber: 49,
		slug: "multilingual-sites",
		title: "Things to watch when building multilingual sites",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer multilingual sites question.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-block-inline-inlineblock",
		questionNumber: 50,
		slug: "block-inline-inlineblock",
		title: "Difference between block, inline, and inline-block",
		track: "gfe75",
		category: "Quiz",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "writeup",
		status: "todo",
		summary: "TODO: Answer block/inline/inline-block differences.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-curry",
		questionNumber: 51,
		slug: "curry",
		title: "Curry",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Curry.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-html-serializer",
		questionNumber: 52,
		slug: "html-serializer",
		title: "HTML Serializer",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve HTML Serializer.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-json-stringify",
		questionNumber: 53,
		slug: "json-stringify",
		title: "JSON.stringify",
		track: "gfe75",
		category: "JavaScript functions",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve JSON.stringify.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-star-rating",
		questionNumber: 54,
		slug: "star-rating",
		title: "Star Rating",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Star Rating.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-image-carousel",
		questionNumber: 55,
		slug: "image-carousel",
		title: "Image Carousel",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Image Carousel.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-progress-bars",
		questionNumber: 56,
		slug: "progress-bars",
		title: "Progress Bars",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Progress Bars.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-like-button",
		questionNumber: 57,
		slug: "like-button",
		title: "Like Button",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Like Button.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-traffic-light",
		questionNumber: 58,
		slug: "traffic-light",
		title: "Traffic Light",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Traffic Light.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-digital-clock",
		questionNumber: 59,
		slug: "digital-clock",
		title: "Digital Clock",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Digital Clock.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-stopwatch",
		questionNumber: 60,
		slug: "stopwatch",
		title: "Stopwatch",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Stopwatch.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-file-explorer",
		questionNumber: 61,
		slug: "file-explorer",
		title: "File Explorer",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve File Explorer.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-tic-tac-toe",
		questionNumber: 62,
		slug: "tic-tac-toe",
		title: "Tic-tac-toe",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Tic-tac-toe.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-transfer-list",
		questionNumber: 63,
		slug: "transfer-list",
		title: "Transfer List",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Transfer List.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-nested-checkboxes",
		questionNumber: 64,
		slug: "nested-checkboxes",
		title: "Nested Checkboxes",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Nested Checkboxes.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-modal-dialog",
		questionNumber: 65,
		slug: "modal-dialog",
		title: "Modal Dialog",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Modal Dialog.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "gfe-data-table",
		questionNumber: 66,
		slug: "data-table",
		title: "Data Table",
		track: "gfe75",
		category: "UI coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/gfe75",
		solutionType: "ui-demo",
		status: "todo",
		summary: "TODO: Solve Data Table.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-balanced-brackets",
		questionNumber: 1,
		slug: "balanced-brackets",
		title: "Balanced Brackets",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl:
			"https://www.greatfrontend.com/interviews/study/blind75/questions/algo/array-balanced-brackets",
		solutionType: "algo-visualizer",
		status: "done",
		summary: "Validate bracket pairing with a stack.",
		approach:
			"Push open brackets; for closers, verify top of stack is matching pair before popping.",
		complexity: "Time: O(n), Space: O(n).",
		tags: ["stack", "parsing", "strings"],
	},
	{
		id: "blind-find-duplicates-in-array",
		questionNumber: 2,
		slug: "find-duplicates-in-array",
		title: "Find Duplicates in Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Find Duplicates in Array.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-find-missing-number-in-sequence",
		questionNumber: 3,
		slug: "find-missing-number-in-sequence",
		title: "Find Missing Number in Sequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Find Missing Number in Sequence.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-maximum-product-in-contiguous-array",
		questionNumber: 4,
		slug: "maximum-product-in-contiguous-array",
		title: "Maximum Product in Contiguous Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Maximum Product in Contiguous Array.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-maximum-sum-in-contiguous-array",
		questionNumber: 5,
		slug: "maximum-sum-in-contiguous-array",
		title: "Maximum Sum in Contiguous Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Maximum Sum in Contiguous Array.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-most-common-elements",
		questionNumber: 6,
		slug: "most-common-elements",
		title: "Most Common Elements",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Most Common Elements.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-array-product-excluding-current",
		questionNumber: 7,
		slug: "array-product-excluding-current",
		title: "Array Product Excluding Current",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Array Product Excluding Current.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-end-of-array-reachable",
		questionNumber: 8,
		slug: "end-of-array-reachable",
		title: "End of Array Reachable",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve End of Array Reachable.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-find-element-in-rotated-array",
		questionNumber: 9,
		slug: "find-element-in-rotated-array",
		title: "Find Element in Rotated Array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Find Element in Rotated Array.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-smallest-element-in-rotated-sorted-array",
		questionNumber: 10,
		slug: "smallest-element-in-rotated-sorted-array",
		title: "Smallest element in rotated sorted array",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Smallest element in rotated sorted array.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bst-kth-smallest-element",
		questionNumber: 11,
		slug: "binary-search-tree-kth-smallest-element",
		title: "Binary Search Tree Kth Smallest Element",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Search Tree Kth Smallest Element.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bst-lowest-common-ancestor",
		questionNumber: 12,
		slug: "binary-search-tree-lowest-common-ancestor",
		title: "Binary Search Tree Lowest Common Ancestor",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Search Tree Lowest Common Ancestor.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-validate-binary-search-tree",
		questionNumber: 13,
		slug: "validate-binary-search-tree",
		title: "Validate Binary Search Tree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Validate Binary Search Tree.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-equal",
		questionNumber: 14,
		slug: "binary-tree-equal",
		title: "Binary Tree Equal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Equal.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-flip-binary-tree",
		questionNumber: 15,
		slug: "flip-binary-tree",
		title: "Flip Binary Tree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Flip Binary Tree.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-level-order-traversal",
		questionNumber: 16,
		slug: "binary-tree-level-order-traversal",
		title: "Binary Tree Level Order Traversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Level Order Traversal.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-maximum-depth",
		questionNumber: 17,
		slug: "binary-tree-maximum-depth",
		title: "Binary Tree Maximum Depth",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Maximum Depth.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-maximum-total-path",
		questionNumber: 18,
		slug: "binary-tree-maximum-total-path",
		title: "Binary Tree Maximum Total Path",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Maximum Total Path.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-rebuild-preorder-inorder",
		questionNumber: 19,
		slug: "binary-tree-rebuilding-from-preorder-and-inorder-traversals",
		title: "Binary Tree Rebuilding from Preorder and Inorder Traversals",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary:
			"TODO: Solve Binary Tree Rebuilding from Preorder and Inorder Traversals.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-serialization-deserialization",
		questionNumber: 20,
		slug: "binary-tree-serialization-and-deserialization",
		title: "Binary Tree Serialization and Deserialization",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Serialization and Deserialization.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-binary-tree-subtree",
		questionNumber: 21,
		slug: "binary-tree-subtree",
		title: "Binary Tree Subtree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Binary Tree Subtree.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bit-counting",
		questionNumber: 22,
		slug: "bit-counting",
		title: "Bit Counting",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Bit Counting.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-bit-reversal",
		questionNumber: 23,
		slug: "bit-reversal",
		title: "Bit Reversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Bit Reversal.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-minimum-coins-for-change",
		questionNumber: 24,
		slug: "minimum-coins-for-change",
		title: "Minimum Coins for Change",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Minimum Coins for Change.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-combinations-for-target-sum",
		questionNumber: 25,
		slug: "combinations-for-target-sum",
		title: "Combinations for Target Sum",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Combinations for Target Sum.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-count-set-bits-binary-number",
		questionNumber: 26,
		slug: "count-set-bits-in-a-binary-number",
		title: "Count Set Bits in a Binary Number",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Count Set Bits in a Binary Number.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-course-dependency",
		questionNumber: 27,
		slug: "course-dependency",
		title: "Course Dependency",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Course Dependency.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-disjoint-intervals",
		questionNumber: 28,
		slug: "disjoint-intervals",
		title: "Disjoint Intervals",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Disjoint Intervals.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-extraterrestrial-language",
		questionNumber: 29,
		slug: "extraterrestrial-language",
		title: "Extraterrestrial Language",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Extraterrestrial Language.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-graph-clone",
		questionNumber: 30,
		slug: "graph-clone",
		title: "Graph Clone",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Graph Clone.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-graph-count-connected-components",
		questionNumber: 31,
		slug: "graph-count-connected-components",
		title: "Graph Count Connected Components",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Graph Count Connected Components.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-is-the-graph-a-tree",
		questionNumber: 32,
		slug: "is-the-graph-a-tree",
		title: "Is the Graph a Tree",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Is the Graph a Tree.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-count-islands-in-grid",
		questionNumber: 33,
		slug: "count-islands-in-a-grid",
		title: "Count Islands in a Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Count Islands in a Grid.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-distinct-paths-in-grid",
		questionNumber: 34,
		slug: "distinct-paths-in-grid",
		title: "Distinct Paths in Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Distinct Paths in Grid.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-find-word-in-grid",
		questionNumber: 35,
		slug: "find-word-in-grid",
		title: "Find Word in Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Find Word in Grid.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-find-words-in-grid",
		questionNumber: 36,
		slug: "find-words-in-grid",
		title: "Find Words in Grid",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Find Words in Grid.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-merge-overlapping-intervals",
		questionNumber: 37,
		slug: "merge-overlapping-intervals",
		title: "Merge Overlapping Intervals",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Merge Overlapping Intervals.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-meeting-calendar",
		questionNumber: 38,
		slug: "meeting-calendar",
		title: "Meeting Calendar",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Meeting Calendar.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-merge-new-interval",
		questionNumber: 39,
		slug: "merge-new-interval",
		title: "Merge New Interval",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Merge New Interval.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-minimum-meeting-rooms-needed",
		questionNumber: 40,
		slug: "minimum-meeting-rooms-needed",
		title: "Minimum Meeting Rooms Needed",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Minimum Meeting Rooms Needed.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-lists-combine-k-sorted",
		questionNumber: 41,
		slug: "linked-lists-combine-k-sorted",
		title: "Linked Lists Combine K Sorted",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Linked Lists Combine K Sorted.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-lists-combine-two-sorted",
		questionNumber: 42,
		slug: "linked-lists-combine-two-sorted",
		title: "Linked Lists Combine Two Sorted",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Linked Lists Combine Two Sorted.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-delete-nth-node-from-end",
		questionNumber: 43,
		slug: "delete-nth-node-from-end-of-linked-list",
		title: "Delete Nth Node from End of Linked List",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Delete Nth Node from End of Linked List.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-list-detect-cycle",
		questionNumber: 44,
		slug: "linked-list-detect-cycle",
		title: "Linked List Detect Cycle",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Linked List Detect Cycle.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-rearrange-linked-list",
		questionNumber: 45,
		slug: "rearrange-linked-list",
		title: "Rearrange Linked List",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Rearrange Linked List.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-linked-list-reversal",
		questionNumber: 46,
		slug: "linked-list-reversal",
		title: "Linked List Reversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Linked List Reversal.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-common-subsequence",
		questionNumber: 47,
		slug: "longest-common-subsequence",
		title: "Longest Common Subsequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Longest Common Subsequence.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-consecutive-number-sequence",
		questionNumber: 48,
		slug: "longest-consecutive-number-sequence",
		title: "Longest Consecutive Number Sequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Longest Consecutive Number Sequence.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-increasing-subsequence",
		questionNumber: 49,
		slug: "longest-increasing-subsequence",
		title: "Longest Increasing Subsequence",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Longest Increasing Subsequence.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-non-repeating-substring",
		questionNumber: 50,
		slug: "longest-non-repeating-substring",
		title: "Longest Non-repeating Substring",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Longest Non-repeating Substring.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-palindromic-substring",
		questionNumber: 51,
		slug: "find-the-longest-palindromic-substring",
		title: "Find the Longest Palindromic Substring",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Find the Longest Palindromic Substring.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-longest-repeating-substring-after-replacements",
		questionNumber: 52,
		slug: "longest-repeating-substring-after-replacements",
		title: "Longest Repeating Substring After Replacements",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Longest Repeating Substring After Replacements.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-matrix-rotation",
		questionNumber: 53,
		slug: "matrix-rotation",
		title: "Matrix Rotation",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Matrix Rotation.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-matrix-spiral-traversal",
		questionNumber: 54,
		slug: "matrix-spiral-traversal",
		title: "Matrix Spiral Traversal",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Matrix Spiral Traversal.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-matrix-zeroing",
		questionNumber: 55,
		slug: "matrix-zeroing",
		title: "Matrix Zeroing",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Matrix Zeroing.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-maximum-water-trapped-between-walls",
		questionNumber: 56,
		slug: "maximum-water-trapped-between-walls",
		title: "Maximum Water Trapped Between Walls",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Maximum Water Trapped Between Walls.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-neighborhood-theft",
		questionNumber: 57,
		slug: "neighborhood-theft",
		title: "Neighborhood Theft",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Neighborhood Theft.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-neighborhood-theft-circular",
		questionNumber: 58,
		slug: "neighborhood-theft-circular",
		title: "Neighborhood Theft (Circular)",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Neighborhood Theft (Circular).",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-number-stream-median",
		questionNumber: 59,
		slug: "number-stream-median",
		title: "Number Stream Median",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Number Stream Median.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-ocean-flow",
		questionNumber: 60,
		slug: "ocean-flow",
		title: "Ocean Flow",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Ocean Flow.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-optimal-stock-trading",
		questionNumber: 61,
		slug: "optimal-stock-trading",
		title: "Optimal Stock Trading",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Optimal Stock Trading.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-pair-sum",
		questionNumber: 62,
		slug: "pair-sum",
		title: "Pair sum",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Pair sum.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-staircase-climbing-combinations",
		questionNumber: 63,
		slug: "staircase-climbing-combinations",
		title: "Staircase Climbing Combinations",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Staircase Climbing Combinations.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-string-anagram",
		questionNumber: 64,
		slug: "string-anagram",
		title: "String Anagram",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve String Anagram.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-string-anagram-groups",
		questionNumber: 65,
		slug: "string-anagram-groups",
		title: "String Anagram Groups",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve String Anagram Groups.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-decode-message",
		questionNumber: 66,
		slug: "decode-message",
		title: "Decode Message",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Decode Message.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-string-palindrome",
		questionNumber: 67,
		slug: "string-palindrome",
		title: "String Palindrome",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Easy",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve String Palindrome.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-palindromic-substrings",
		questionNumber: 68,
		slug: "palindromic-substrings",
		title: "Palindromic Substrings",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Palindromic Substrings.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-segment-words",
		questionNumber: 69,
		slug: "segment-words",
		title: "Segment Words",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Segment Words.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-shortest-substring-containing-characters",
		questionNumber: 70,
		slug: "shortest-substring-containing-characters",
		title: "Shortest Substring Containing Characters",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Hard",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Shortest Substring Containing Characters.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-sum-without-addition",
		questionNumber: 71,
		slug: "sum-without-addition",
		title: "Sum Without Addition",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Sum Without Addition.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-task-coordination",
		questionNumber: 72,
		slug: "task-coordination",
		title: "Task Coordination",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Task Coordination.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-trie-prefix-tree",
		questionNumber: 73,
		slug: "trie-prefix-tree",
		title: "Trie (Prefix Tree)",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Trie (Prefix Tree).",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-triplet-sum",
		questionNumber: 74,
		slug: "triplet-sum",
		title: "Triplet Sum",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Triplet Sum.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
	{
		id: "blind-word-finder",
		questionNumber: 75,
		slug: "word-finder",
		title: "Word Finder",
		track: "blind75",
		category: "Algorithmic coding",
		difficulty: "Medium",
		sourceUrl: "https://www.greatfrontend.com/interviews/blind75",
		solutionType: "code-and-tests",
		status: "todo",
		summary: "TODO: Solve Word Finder.",
		approach: "TODO",
		complexity: "TODO",
		tags: [],
	},
];

export function getQuestionsByTrack(track: Track): Question[] {
	return QUESTIONS.filter((question) => question.track === track);
}

export function getQuestionBySlug(track: Track, slug: string): Question | null {
	return (
		QUESTIONS.find(
			(question) => question.track === track && question.slug === slug,
		) ?? null
	);
}
